In [107]:
import numpy as np
from chainer import cuda, Function, FunctionSet, gradient_check, Variable, optimizers
import chainer.functions as F
import chainer.optimizers

In [11]:
x_data = np.array([5], dtype=np.float32) #numpyの配列オブジェクト生成

In [13]:
len(x_data),x_data[0] #配列数１つ、値5という配列が生成された

(1, 5.0)

In [14]:
x = Variable(x_data) #Variableでchainerでつかうオブジェクトに変換

In [16]:
y = x**2 - 2 * x + 1 #y=x2−2x+1を実行すると・・・
y.data

array([ 16.], dtype=float32)

In [20]:
y.backward() #yは計算結果だけでなく、計算過程も覚えているため、back propagationができる

In [21]:
x.grad #back propagationをした後で、xの勾配を求めることができる

array([ 8.], dtype=float32)

In [23]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)) #多次元配列の場合・・・

In [24]:
y = x**2 - 2*x + 1 #この式をやると

In [25]:
y.data #こういう式になって

array([[  0.,   1.,   4.],
       [  9.,  16.,  25.]], dtype=float32)

In [26]:
np.ones((2, 3), dtype=np.float32) #np.oneで1埋めした行列とかで

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [27]:
y.grad = np.ones((2, 3), dtype=np.float32) #任意の初期値を設定しないといけない

In [28]:
y.backward() #するとback propagationで

In [29]:
x.grad #勾配が計算できる

array([[  0.,   2.,   4.],
       [  6.,   8.,  10.]], dtype=float32)

In [42]:
f = F.Linear(3, 2) #関数の指定。これは恒等関数 f(x)=Wx+b

In [43]:
f.W #デフォルトでは重みwはランダムに初期化される

array([[ 0.25072467,  0.74700743, -1.33170593],
       [ 0.40668043, -0.2747542 ,  0.73473263]], dtype=float32)

In [44]:
f.b #バイアスは0で初期化される

array([ 0.,  0.], dtype=float32)

In [45]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32))

In [46]:
y = f(x)

In [47]:
y.data

array([[-2.25037813,  2.0613699 ],
       [-3.25229955,  4.66134644]], dtype=float32)

In [55]:
y.grad = np.ones((2, 2), dtype=np.float32) #yの勾配の初期化

In [56]:
y.backward()

In [57]:
f.gW

array([[ 5.,  7.,  9.],
       [ 5.,  7.,  9.]], dtype=float32)

In [58]:
f.gb

array([ 2.,  2.], dtype=float32)